### ISSUE TITLE
If the gcloud is on the path, the plugin should use that to find the SDK path

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/appengine-plugins-core#267]
See https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/118

**Comment by patflynn** [comment]
I believe we were already doing something like this in intellij using 'which' or 'where'.  I assumed this was happening in the core lib but I guess it's not.

**Comment by chanseokoh** [comment]
FWIW, the library searches `$PATH`. But, yeah, it doesn't actually invoke `gcloud` but only looks for `"google-cloud-sdk/bin" in `$PATH`.

https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/src/main/java/com/google/cloud/tools/appengine/cloudsdk/PathResolver.java#L40
https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/src/main/java/com/google/cloud/tools/appengine/cloudsdk/PathResolver.java#L74

I guess it'd be much safer to actually invoke `gcloud` rather than relying on [some Linux commands](http://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then).

**Comment by briandealwis** [comment]
See also https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/131#issuecomment-227783960

**Comment by loosebazooka** [comment]
fixed by #295
