### ISSUE TITLE
Devappserver1 throws exception on conflicting env vars

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/appengine-plugins-core#403]
When environment vars with the same key, but differing values, are configured in appengine-web.xml and the client environment, devappserver1 throws an error:

```
com.google.appengine.tools.development.EnvironmentVariableChecker$IncorrectEnvironmentVariableException: One or more environment variables have been configured in appengine-web.xml that have missing or different values in your local environment. We recommend you use system properties instead, but if you are interacting with legacy code that requires specific environment variables to have specific values, please set these environment variables in your environment before running.
[Mismatch environmentVariableName=foo environmentVariableValue=asdfasdf appEngineWebXmlValue=test appEngineWebXmlFile=/usr/local/google/home/eshaul/IdeaProjects/untitled163/out/artifacts/untitled163_war_exploded/WEB-INF/appengine-web.xml]
```

We should update the env var processing to take the value from appengine-web.xml and warn the user that the value configured in their environment is ignored.

**Comment by elharo** [comment]
This is in devappserver code, not appengine-plugins-core.

**Comment by elharo** [comment]
As best I can tell this is all in the devappserver code, and the default is to throw an exception. There is a method to call to change this but no command line argument, so we can't stright-forwardly adjust this.

If you still want this you'll need to open an RFE with the devappserver tracker to either set the default to log only, or to add an extra command line flag to chaneg the default. It can't be fixed in this repo.
