### ISSUE TITLE
Add GAE_ENV and GAE_RUNTIME environment variables for local development

### ISSUE THREAD

**Issue by ifigotin** [GoogleCloudPlatform/appengine-plugins-core#444]
Please add the following environment variables to dev app server environment:
GAE_ENV = "localdev"
GAE_RUNTIME = "java7" or "java8" (depending on which runtime is used).

These variables are now available in GAE Java runtime, and should also be available in local development environment.

**Comment by ludoch** [comment]
I am doing this in the original maven plugin as well.
We did it in kickstart (java)
We want this for all IDE plugins and new MAven/Gradle plugins

**Comment by ludoch** [comment]
internal spec go/gae-sr-runtime-contract

**Comment by elharo** [comment]
Could these be set in dev_appserver.sh/dev_appserver.py which would cascase to all environments?

**Comment by ifigotin** [comment]
In dev_appserver.sh we don't know yet if the runtime being used is java8 or java7, so this approach may not work.

**Comment by elharo** [comment]
Nonetheless GAE_ENV = "localdev" should be able to be set unconditionally at the lowest level in dev_appserver. Given that some people will run dev_appserver directly, without a tool, this needs to be done.

**Comment by elharo** [comment]
The runtime will probably need to be part of DefaultRunConfiguration and on the Eclipse side we'll need to set this in `LocalAppEngineServerLaunchConfiguration.generateServerRunConfiguration`.

**Comment by elharo** [comment]
Could the runtime be read from appengine-web.xml? dev_appserver should know where this file is.

**Comment by ludoch** [comment]
yes.

**Comment by loosebazooka** [comment]
@ifigotin it looks like all of this can be determined by the dev_appserver? Is there a reason they need to be set before launching the process?

**Comment by ludoch** [comment]
What about devappserver1?

**Comment by elharo** [comment]
Both devappservers should be able to do this.

**Comment by ifigotin** [comment]
Could you clarify if you are suggesting to parse appengine-web.xml in a shell script to figure out the runtime?

**Comment by ifigotin** [comment]
The dev_appserver.sh script (which I believe we refer to as dev app server 1?) is a simple script that delegates to com.google.appengine.tools.KickStart class to do the work. We already modified KickStart to handle the variables. 
I believe we were referring to dev app server 2?

**Comment by loosebazooka** [comment]
@ifigotin for devappserver1 we call into DevAppServerMain directly, presumably this is why we need to set them before starting the process?

**Comment by loosebazooka** [comment]
Do we have a process in place to make sure Kickstart and other java tools are in sync?

**Comment by elharo** [comment]
Yes, I am proposing that one way or another dev_appserver, 1 & 2, set these variables. 

They have the information they need to set these and they need to do this anyway for users who call them directly. There's no reason to multiply this work by also doing it in all the tools that delegate to the dev_appservers.

**Comment by ifigotin** [comment]
Kickstart sets the correct values already, so I believe we've covered dev_appserver.sh path. 
I'm not familiar with devappserver2. Maybe @ludoch will comment on this one.

**Comment by ludoch** [comment]
Tools are not calling kickstart, only our shell script for devappserver1.
So common is the right place in the process builder code.
For devappserver2, yes, env code has to be done in the python code that
starts the given module/service.

Ludo

**Comment by loosebazooka** [comment]
@elharo I think the long term solution is to somehow call into kickstart main without starting a new process, which is what the gradle-appengine-plugin does. However that might require a pretty large rewrite on our side, since it probably wouldn't act nice with our exposed API. And maybe the even longer term solution is to move back to dev_appserver2 when it is ready.
Despite the fact that this does add a maintenance/synchronization burden, it appears to be a reasonable expectation for us to do this given that our current runner does mimic much of what kickstart is doing anyway.
What do you think?

**Comment by elharo** [comment]
Doing this here is not free. For instance,  CT4E will have to do non-trivial work to pass along the runtime to the local server. Now that I think about it, we'll have to parse the appengine-web.xml because we don't even know this for an imported project, so it's really a question of in which project we parse appengine-web.xml to find this out. 3 possibilities:

1. Ct4E/IntelliJ
2. appengine-plugins-core
3. dev_appserver

No. 1 is more work than No. 2.
I'm not sure whether No. 2 or No. 3 is easier. 

GAE_ENV can be set unconditionally in dev_appserver in a single line. I don't see any reason not to do that in the dev_appserver code ASAP. That's more robust than relying on tools higher up the chain.

**Comment by briandealwis** [comment]
The only reason to do this from CT4{E,IJ} or appengine-plugins-core is that devappserver1 cannot change its environment using only API.  The internal copy of the environment seen by Java [can be changed via reflection](https://stackoverflow.com/a/7201825/600339) (though it's a local copy, and changes won't be propagated to children).

**Comment by loosebazooka** [comment]
Does eclipse not use the launcher from appengine-plugins-core?

I figured we'd do it in appengine-plugins-core so all tools would benefit.

**Comment by briandealwis** [comment]
Sorry, I somehow thought we were looking to pass along a project ID.

**Comment by loosebazooka** [comment]
Q you wanna take a stab at this?

**Comment by elharo** [comment]
I still do not think this is the right place to fix this. Why is this not being done in dev_appserver?

**Comment by ludoch** [comment]
dev_appserver? the sh script? the py script? something else?

**Comment by loosebazooka** [comment]
@elharo because we manage starting the devappserver process. So we have to set the environment on the process. This is an issue with starting the process ourselves, it's not applicable to dev_appserver2 though since that manages the whole thing. We could potentially call into KickStart#main instead of DevAppServer#main ? would have to explore that possibility.
