### ISSUE TITLE
Proxy configuration for Downloader.

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/appengine-plugins-core#457]
@briandealwis Can you explain how eclipse might pass proxy information. The downloader wont specifically by called by the tool developer. I expect though, that a passthrough will be available. Just wondering what you want to passthough.

**Comment by loosebazooka** [comment]
@briandealwis any ideas?

**Comment by briandealwis** [comment]
Sorry, missed this @loosebazooka.  Good question.  We've been using `google-http-client` where we provide a configured `java.net.Proxy` instances via an explicit TransportFactory.  The Eclipse Proxy support does update the various `http.proxy*`, `https.proxy*`, and `socksProxy*` properties, so it looks like nothing that's explicitly necessary since you're using `URLConnection`.

**Comment by loosebazooka** [comment]
Yeah, the sys properties configure the proxy automatically. I'll leave this open because I'm not completely sure about the interaction and have not tested it.

**Comment by loosebazooka** [comment]
this is stale.
