### ISSUE TITLE
Survey to remove unused utilities from code

### ISSUE THREAD

**Issue by loosebazooka** [GoogleCloudPlatform/appengine-plugins-core#576]
Can you confirm if you are using these in your code? Reassign as necessary.

| Feature                         | Build                             | Eclipse                          | Intellij 
| ------------------------------ | ------------------------------ | ------------------------------ | ------------------------------ |
| CloudSdkAppEngineGenConfig | no | no | no |
| CloudSdkAppEngineInstances | no | no | no |
| CloudSdkAppEngineLogs | no | no | no |
| CloudSdkAppEngineServices | no | no | no |
| CloudSdkAppEngineVersions | no | no | yes |

**Comment by etanshaul** [comment]
if curious, IntelliJ is using `CloudSdkAppEngineVersions` for the ability to stop a particular version of an AE app

**Comment by etanshaul** [comment]
hmm..it looks like this is flex only (we don't enable it for AE standard, I _think_ thats because of the inability to scale to 0 in standard).  It is available after the user deploys the project:
<img width="470" alt="screen shot 2018-03-29 at 4 46 44 pm" src="https://user-images.githubusercontent.com/1735744/38112707-c7c77464-3370-11e8-8534-b0437a9e14d6.png">

Notice the greyed out "undeploy" button (because the screenshot is from a standard app)

@patflynn may recall more details about this

**Comment by elharo** [comment]
Is this related to #335?
